name: build
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - run: go mod tidy
      - run: git diff --exit-code
      - run: go build -race ./...
      - run: go test -race -failfast ./...
      - name: Build darwin binary
        if: matrix.os == 'macos-latest'
        run: go build -o crush .
      - name: Upload darwin binary
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: crush-darwin
          path: crush
